"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """
[╭─](purple) $os$directory$git_branch$python$nix_shell$fill$time
[╰─](purple) $character
"""

[fill]
disabled = false
symbol = ' ∙'
style = '#f5e0dc'

[directory]
style = "purple"

[line_break]
disabled = false

[git_branch]
symbol = " "
style = "purple"

[os]
disabled = false
style = 'purple'
format = '[$symbol ]($style)'

[python]
symbol = " "
style = "yellow"
format = "via [${symbol}${version}( ($virtualenv))]($style) "
version_format = "v${raw}"
python_binary = ["python3", "python"]
detect_extensions = ["py", "ipynb"]
detect_files = [
  ".python-version",
  "Pipfile",
  "__init__.py",
  "pyproject.toml",
  "requirements.txt",
  "setup.py",
  "tox.ini",
  "uv.lock",
]
detect_folders = [".venv", "venv"]
generic_venv_names = [".venv", "venv"]

[nix_shell]
symbol = " "
style = "blue"
format = "via [$symbol$state( ($name))]($style) "
heuristic = false

[time]
disabled = false
time_format = '%R'
style = '#f5e0dc'
format = '[ $time]($style)'

[character]
success_symbol = "[󰄛](purple)"
error_symbol = "[󰄛](red)"

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false

[os.symbols]
Windows = ''
Ubuntu = '󰕈'
openSUSE = ''
Raspbian = '󰐿'
Mint = '󰣭'
Macos = ''
Manjaro = ''
Linux = '󰌽'
Gentoo = '󰣨'
Fedora = '󰣛'
Alpine = ''
Amazon = ''
Android = ''
Arch = '󰣇'
Artix = '󰣇'
CentOS = ''
Debian = '󰣚'
Redhat = '󱄛'
RedHatEnterprise = '󱄛'
NixOS       = ''
Pop         = ''
EndeavourOS = ''
Kali        = ''
FreeBSD     = ''
Elementary  = ''
Zorin       = ''
Unknown     = '󰋖'
