#FONT
font_size 11
cursor_trail 5

# #BACKGROUND#############################################################################
background_opacity 0.65
dynamic_background_opacity yes
# Kitty Configuration

map ctrl+enter launch --location=vsplit
map ctrl+shift+enter launch --location=hsplit
map ctrl+f launch --type=overlay --cwd=current fuzzyvim

# General Settings
window_padding_width 8



# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
