Net/ThemeName "Catppuccin-Dark"
Net/IconThemeName "Yaru-magenta-dark"
Gtk/CursorThemeName "Nordzy-catppuccin-frappe-lavender"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 1
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
